### ISSUE TITLE
four letter password sign up gives blank screen

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#1]
When using a four letter password to sign up, the sign up returns with a blank screen.  BE network response says `instance.password does not meet minimum length of 5`

Steps to reproduce:
1. Navigate to sign up.
2. Use "aaaa" for a password
3. Fill rest out with valid info.
4. Click sign up.
5. Observe that the page goes blank

See below:
![image](https://github.com/user-attachments/assets/7dd112dd-a7a2-46ff-95a6-1a1793dd6b9f)

**Comment by OspreyFly** [comment]
My solution is to conditionally render an element to warn users, then return to end the submit function.

**Comment by CodyTVWeber** [comment]
This looks to be fixed.
