### ISSUE TITLE
Unable to scroll

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#10]
I am unable to scroll on any page.

Steps to reproduce:
1. Navigate to insects page
2. Attempt to scroll with mouse wheel

![image](https://github.com/user-attachments/assets/357821e8-ddc8-44f3-bafa-4642ae7f9efa)

**Comment by OspreyFly** [comment]
After going through user flow starting from each anon/login/signup to filtering the insect page and adding to cart, then going to checkout, removing items, and finally successfully submitting the order. I'm still not able to replicated this bug.
