### ISSUE TITLE
Unable to sign up or login

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#11]
Seems like the elements are behind the title and navbar.  So unable to click the input fields.

This issue is on both:
- [ ] Sign up page
- [ ] Login page

![image](https://github.com/user-attachments/assets/4c274f1b-e41d-4b90-8448-fb5c948c467f)

**Comment by OspreyFly** [comment]
Not sure how this was possible, but I don't see this bug either.

**Comment by CodyTVWeber** [comment]
Login issue fixed
