### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#2]
- [x] Title contrast is too low.  Low eyesight people will not be able to see it.  
  - See https://webaim.org/resources/contrastchecker/ for testing out colors.  (I will not be picky, but this is a good lesson in basic website development that users can see the title properly.)
- [x] Plus button for adding to cart does not give UI indicator that button is disabled.

**Comment by OspreyFly** [comment]
I updated the Homepage view to feature media content. The Navbar shows the title for the site with bright lettering on a dark background. I added state to the InsectCard component to display an add or remove button based on if it is found in the cart. The add and remove buttons are different colors and show +/- respectively.
