### ISSUE TITLE
Checking out order goes to loading page

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#3]
When submitting the checkout, the page goes to loading.  This seems to be an undesirable state.  The users will likely be confused and may even believe the order was not made.

**Comment by OspreyFly** [comment]
My solution is to redirect the user back to the insect shopping view and clear the cart. An integrated checkout API would be the ideal page to navigate to next in a future version. I also included messages about the order if it is not successful and if it is a duplicate order that has been denied.

**Comment by CodyTVWeber** [comment]
Would it be easy to add a success alert/notification if the order is created?

**Comment by OspreyFly** [comment]
I added an alert call that pauses execution and notifies user that their order was successful. When they click ok it continues to redirect them to the store like before.

**Comment by CodyTVWeber** [comment]
Looks fixed!
