### ISSUE TITLE
Login attempt with non-existent user causes screen to go blank

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#5]
Login attempt with non-existent user causes screen to go blank.

Opportunities:
- [ ] Users need an indicator that their login attempt failed.
- [ ] Users will likely want to reattempt their login.  (maybe they fat-fingered their login info)

![image](https://github.com/user-attachments/assets/36063e4c-f5db-4689-87ba-a10efefb1855)

**Comment by OspreyFly** [comment]
I added setFormErrors state that conditionally renders my Alert component. When the login request fails, the state is set and an explanation is provided. The formErrors state is updated upon form submission.

**Comment by CodyTVWeber** [comment]
This looks like it is fixed from what I am seeing :)
