### ISSUE TITLE
Home page opportunities

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#6]
Here are a couple home page opportunities:

- [ ] The tic tok element is blank
- [ ] The links on the home page are black on dark grey which is very difficult for users to see.  (Exactly the same as the Title before).  This should be more visible for users.

![image](https://github.com/user-attachments/assets/226e134c-3647-4dd4-9c8e-2d6bbc07d01c)

**Comment by OspreyFly** [comment]
Rather than troubleshoot the Tik-Tok embed, I decided to use YouTube embed instead. We are likely to host videos and streams on YouTube anyways and it's easier to work with.

**Comment by CodyTVWeber** [comment]
Looks fixed.
