### ISSUE TITLE
Need meaningful error alert for users to understand issue

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#7]
When attempting to Sign up with invalid info OR attempting to create a user that already exists, it gives a notification about a 400 error.  This is not understandable by the user about how to fix their issue.  Giving a specific human understandable message to the user will help them to fix their issues while attempting to sign up.

So the three ways in which I recreated this issue:
- [x] Attempting to create a user that already exists
- [x] Attempting to create a user that has an empty username
- [x] Attempting to create a user with an empty email 

![image](https://github.com/user-attachments/assets/afec54e2-06f1-4557-bba0-766b3bf9ec4a)

**Comment by OspreyFly** [comment]
I added checks in the submit function to update the formErrors state of any form fields that need to be changed for a successful submission. If the submission fails it tells you that the account already exists.

**Comment by CodyTVWeber** [comment]
Looks fixed
