### ISSUE TITLE
Searching for empty does not give all results

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#8]
So when I search "ant", the search works, but when I attempt to clear out my search to see all results, nothing changes.

![image](https://github.com/user-attachments/assets/af6cd504-0fca-4b5c-981f-52b1a79cdee7)

**Comment by OspreyFly** [comment]
I added a "Clear Filters" button that will reset the state with no filter.

**Comment by CodyTVWeber** [comment]
Looks fixed
