### ISSUE TITLE
Attempting to login with non-existent user causes blank screen

### ISSUE THREAD

**Issue by CodyTVWeber** [OspreyFly/fuzzy-phids-frontend#9]
Looks like after attempting to login to non-existent user, there is a malformed JSX.

Steps to reproduce:
1. Navigate to login page
2. Type in "somenonexistentuser" in username field
3. Type in "anything" in password field
4. Click login

![image](https://github.com/user-attachments/assets/78a3f166-85c3-4ba2-8f65-4e8b9c091acc)

**Comment by OspreyFly** [comment]
I use the username from the form data to search the database for the user. If it fails, it sets the error state accordingly.

**Comment by CodyTVWeber** [comment]
Fixed
